
# ─── App ──────────────────────────────────────────────────
spring.application.name=auth-service
server.port=${PORT:8080}

# ─── MySQL ────────────────────────────────────────────────
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ─── JPA / Hibernate ──────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ─── Redis ────────────────────────────────────────────────
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.ssl.enabled=true

spring.data.redis.url=${REDIS_URL}



# ─── JWT ──────────────────────────────────────────────────
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:604800000}

# ─── Email (Gmail) ────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ─── Other ────────────────────────────────────────────────
spring.main.allow-circular-references=true

# ─── Rate Limiting ────────────────────────────────────────
spring.main.allow-circular-references=true

# ─── Swagger ──────────────────────────────────────────────
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

server.forward-headers-strategy=framework

server.error.include-message=always
server.error.include-stacktrace=always
